### ISSUE TITLE
Bug located in ...

### ISSUE THREAD

**Issue by Ouam74** [ansys/pyedb#265]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Placing an encrypted Parasolid component XYZ with the EDB API and importing the EDB into Electronics Desktop produces the following warning message:

```
Component definition XYZ is encrypted in ACIS and simulation of such components is not supported.
```

Attempting to simulate the resulting design results in the following error messages:

```
XYZ: Analysis on components encrypted in ACIS is not supported.
Failed to collect initial geometry data for: XYZ
3D Components in the design are unsupported. Update definition.
```

The component, however, is in fact a Parasolid component and can be manually placed via Electronics Desktop and solutions will work as expected in this case.

### Steps To Reproduce

Extract the attached ZIP file in convenient location (Can be found under the Ansys 'bug reporting' system under TFS -->1004280)
In the extraction location, use a Command Window to create a new Python virtual environment and install ansys-edb-core:

python -m venv venv
venv\scripts\activate
pip install ansys-edb-core

Run the following script:
```
import os
from pathlib import Path
import tempfile

from ansys.edb.core.database import Cell
from ansys.edb.core.database import Database
from ansys.edb.core.layout import McadModel
from ansys.edb.core.session import session


edb_input_path = Path("ind_test_start.aedb")
edb_output_path = tempfile.mkdtemp(".aedb", prefix="ind_test_", dir=Path(__file__).parent)
# a3dcomp_path = "LQP02TN0N2_C_S_PS.a3dcomp"
a3dcomp_path = "short_0408.a3dcomp"


with session(os.environ["ANSYSEM_ROOT241"], 21983):
    db = Database.open(edb_input_path.as_posix(), False)
    try:
        db.save_as(edb_output_path)
        cell: Cell = db.top_circuit_cells[0]
        model = McadModel.create_3d_comp(layout=cell.layout, filename=a3dcomp_path)
        cell_instance = model.cell_instance
        cell_instance.placement_layer = cell.layout.layer_collection.find_by_name("L1")
        db.save_as(edb_output_path)
        print(f"EDB saved to {edb_output_path}")
    finally:
        db.close()
```

Note the script prints a location of an EDB it created with the placed component; open that EDB in Electronics Desktop
Note the warning message shown in the description
Launch the Setup1 solution setup and note the error messages shown in the description
Optional steps to confirm 3D Component is OK for simulation:

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

ansys-pythonnet==3.1.0rc3
attrs==23.2.0
cffi==1.16.0
clr-loader==0.2.6
defusedxml==0.7.1
fonttools==4.47.2
fpdf2==2.7.7
json5==0.9.14
jsonschema==4.21.0
jsonschema-specifications==2023.12.1
numpy==1.26.3
pillow==10.2.0
plumbum==1.8.2
psutil==5.9.7
pyaedt==0.7.10
pycparser==2.21
pywin32==306
referencing==0.32.1
rpds-py==0.17.1
rpyc==5.3.1

**Comment by SMoraisAnsys** [comment]
Hi @Ouam74 I think you might have posted this issue to the wrong repository.
Seems like your error is associated to [pyedb-core](https://github.com/ansys/pyedb-core) and not `pyedb`.

**Comment by svandenb-dev** [comment]
closing this issue as it is related to Product bugs not pyedb
