### ISSUE TITLE
edb.core_siwave.create_circuit_port_on_pin

### ISSUE THREAD

**Issue by boyang2022** [ansys/pyedb#287]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

```python
edb.core_siwave.create_circuit_port_on_pin(pos_pin=cap.pins["1"], neg_pin=cap.pins["2"])
```

Error:
PyEDB ERROR: ATTRIBUTE ERROR on _create_terminal_on_pins
PyEDB ERROR: 'Settings' object has no attribute 'retry_n_times_time_interval'
PyEDB ERROR:   File "D:\py_projects\pyedb_prj\.venv\lib\site-packages\pyedb\dotnet\edb_core\siwave.py", line 252, in create_circuit_port_on_pin
PyEDB ERROR:     return self._create_terminal_on_pins(circuit_port)
PyEDB ERROR:   File "D:\py_projects\pyedb_prj\.venv\lib\site-packages\pyedb\dotnet\edb_core\siwave.py", line 127, in _create_terminal_on_pins
PyEDB ERROR: Method arguments: 
PyEDB ERROR:     source = <pyedb.dotnet.edb_core.edb_data.sources.CircuitPort object at 0x000001B0FF1F1DF0> 

### Steps To Reproduce

```python
edb.core_siwave.create_circuit_port_on_pin(pos_pin=cap.pins["1"], neg_pin=cap.pins["2"])
```

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

ansys-pythonnet==3.1.0rc3
cffi==1.16.0
cfgv==3.4.0
clr-loader==0.2.6
colorama==0.4.6
distlib==0.3.8
exceptiongroup==1.2.0
filelock==3.13.1
identify==2.5.35
iniconfig==2.0.0
nodeenv==1.8.0
numpy==1.26.4
packaging==24.0
platformdirs==4.2.0
pluggy==1.4.0
pre-commit==3.6.2
pycparser==2.21
pyedb==0.5.2
pytest==8.1.1
pywin32==306
PyYAML==6.0.1
tomli==2.0.1
virtualenv==20.25.1

**Comment by gkorompi** [comment]
Hello Bo, do you have a script file you can share?

**Comment by boyang2022** [comment]
hello @gkorompi, please try the following:

```python
import pyedb
from pyedb.generic.general_methods import generate_unique_folder_name
from pyedb.misc.downloads import download_file


def main():
    temp_folder = generate_unique_folder_name()
    targetfile = download_file('edb/ANSYS-HSD_V1.aedb', destination=temp_folder)

    edbapp = pyedb.Edb(edbpath=targetfile, edbversion="2023.2")
    cap = edbapp.components.capacitors["C1"]
    edbapp.core_siwave.create_circuit_port_on_pin(pos_pin=cap.pins["1"], neg_pin=cap.pins["2"])


if __name__ == "__main__":
    main()
```

**Comment by gkorompi** [comment]
Hello @boyang2022, for the moment please try the following script. 
In the two cases "pins" are defined as different objects. I will update it to work for both cases. In the meantime please use the following: 

import pyedb
from pyedb.generic.general_methods import generate_unique_folder_name
from pyedb.misc.downloads import download_file


def main():
    temp_folder = generate_unique_folder_name()
    targetfile = download_file('edb/ANSYS-HSD_V1.aedb', destination=temp_folder)

    edbapp = pyedb.Edb(edbpath=targetfile, edbversion="2023.2")
    cap = edbapp.components.capacitors["C1"]
    pins = edbapp.components.get_pin_from_component("C31")
    edbapp.siwave.create_voltage_source_on_pin(pos_pin=pins[0], neg_pin=pins[1])


if __name__ == "__main__":
    main()
