### ISSUE TITLE
Bug located in edb.stackup.load(). XML works in Hfss3dlayout GUI but doesn't work with PyEDB.

### ISSUE THREAD

**Issue by gene820715** [ansys/pyedb#289]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Two issues:

1. edb.stackup.load(<path_to_xml>) unable to import xml where stackup layer names are changed.  It would say something like _SOLDER_MASK doesn't exist in xml_. However, in the xml file, I am providing same number of layers inside the current stackup. The same xml file has no issue to be imported inside Hfss3dlayout GUI.
2. Surface roughness model does not get imported. E.g.
```
     <GroissSurfaceRoughness Roughness="2.55mm"/>
     <GroissBottomSurfaceRoughness Roughness="2.55mm"/>
     <GroissSideSurfaceRoughness Roughness="2.55mm"/>
```

### Steps To Reproduce

1. Load a project with a stackup in Hfss3dlayout GUI
2. Change the stackup by changing names of some layer, and add surface roughness to some layers
3. Export the changed stackup **xml**
4. Using PyEDB, open the **original edb** (unmodified stackup)
5. Try edb.stackup.load(<path_to_xml>)

### Which Operating System are you using?

Linux

### Which Python version are you using?

3.8

### Installed packages

PyAEDT and all related packages

**Comment by gkorompi** [comment]
Hello @gene820715, just to confirm. In steps 2 and 3 are you using Pyaedt, Pyedb or the changes are made manually in the GUI?
