### ISSUE TITLE
Bug located in edb.components.create_rlc_component(). Cannot short (r=0).

### ISSUE THREAD

**Issue by gene820715** [ansys/pyedb#302]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

With current design of the function, I cannot create a component that's shorted (r=0).
```
if r_value:
    ...
else:
    rlc.REnabled = False
```

### Steps To Reproduce

1. `edb.components.create_rlc_component([<pin1>, <pin2>], 'test_component', 0,0,0, False)` + save & close edb
2. Open/Import edb in AEDT GUI
3. Locate the component, it would have R not enabled

### Which Operating System are you using?

Linux

### Which Python version are you using?

3.8

### Installed packages

pyaedt 0.8.6
pyedb 0.7.0
Other needed packages

**Comment by svandenb-dev** [comment]
@gene820715 are you sure you want to create zero value resistors ? because when imported in aedt it will be defaulted to lowest one, not zero.

**Comment by gkorompi** [comment]
Nevertheless, there is not the option in pyaedt to assign value 0 to R, L or C, but they are always defined as not enabled. Please see pull request, and give me your opinion

**Comment by gene820715** [comment]
@svandenb-dev  Hm... then what is the proper way to create a logical short? I was thinking to have a zero value resistor, and then import in aedt. Currently I don't know a way to do that in edb so I cannot test whether the import works or not.

**Comment by gene820715** [comment]
@gkorompi The changes in pull request looks good to me.

**Comment by gene820715** [comment]
Tested and working!
