### ISSUE TITLE
Missing dependency declaration or ImportError check for matplotlib

### ISSUE THREAD

**Issue by isaacansys** [ansys/pyedb#351]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

https://github.com/ansys/pyedb/blob/c5a03f383e7f2b2bd8fc809012746fbe2cbe6d6c/src/pyedb/dotnet/edb_core/stackup.py#L36 imports from `matplotlib` outside a `try-except ImportError` block, but `matplotlib` is not in the primary dependencies list in `pyproject.toml`.

### Steps To Reproduce

1. Create a fresh virtual environment and activate it
2. `pip install pyedb` to install PyEDB with only the base dependency set
3. Run the following interaction in a Python interactive shell

```
(venv) C:\scratch>python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyedb import Edb
>>> db = Edb(edbversion="2024.1")
C:\scratch\venv\lib\site-packages\pyedb\dotnet\edb_core\edb_data\components_data.py:36: UserWarning: The NumPy module is required to run some functionalities of EDB.
Install with

pip install numpy

Requires CPython.
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\scratch\venv\lib\site-packages\pyedb\generic\design_types.py", line 108, in Edb
    from pyedb.dotnet.edb import Edb as app
  File "C:\scratch\venv\lib\site-packages\pyedb\dotnet\edb.py", line 87, in <module>
    from pyedb.dotnet.edb_core.stackup import Stackup
  File "C:\scratch\venv\lib\site-packages\pyedb\dotnet\edb_core\stackup.py", line 36, in <module>
    import matplotlib.colors
ModuleNotFoundError: No module named 'matplotlib'
>>>
```

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

```
annotated-types==0.6.0
ansys-pythonnet==3.1.0rc3
cffi==1.16.0
clr-loader==0.2.6
pycparser==2.22
pydantic==2.6.4
pydantic_core==2.16.3
pyedb==0.7.1
pywin32==306
toml==0.10.2
typing_extensions==4.11.0
```

**Comment by gkorompi** [comment]
Hello @isaacansys, please use pip install pyedb[full]
Then use  pip freeze to check the dependencies: 
![image](https://github.com/ansys/pyedb/assets/156683163/b6381156-1fb5-4ed8-bbcb-72b7c2abb747)

**Comment by isaacansys** [comment]
@gkorompi thank you.  For now I've pinned the dependency in my project to <0.7.1 to work around this.
