### ISSUE TITLE
Failing to detect correct Ansys version with mesh via plating

### ISSUE THREAD

**Issue by svandenb-dev** [ansys/pyedb#352]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

The current EDB version is not working properly to detect Ansys version 2024.1 or higher with setting mesh_via_plating.

### Steps To Reproduce

NA

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

NA

**Comment by gkorompi** [comment]
The information can be transferred to older versions of edb, hence it depends only in the aedt version. If the edb is 23.2 and the aedt version in which imported is 24.2 then the option will be corretly displayed. 
The reason why it does not find the correct version, is that the dataset holds the initial version, and it is updated only when saved. IMO there is no reason to keep the if statement that checks the version, as soon as the edb file correctly transfers the information.
