### ISSUE TITLE
BUG: nets.get_plot_data() does not for empty input

### ISSUE THREAD

**Issue by gkorompi** [ansys/pyedb#366]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

BUG: nets.get_plot_data() does not for empty input

### Steps To Reproduce

NA

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

NA

**Comment by SMoraisAnsys** [comment]
Can you provide a code reproducer to illustrate the issue ?

**Comment by gkorompi** [comment]
import pyedb
import os
from pyedb.dotnet.edb import Edb
edbapp = Edb(r"C:\Users\gkorompi\PycharmProjects\pyedb\tests\example_models\TEDB\ANSYS-HSD_V1.aedb")
edbapp.nets.get_plot_data()
