### ISSUE TITLE
Bug located in edb.stackup.export

### ISSUE THREAD

**Issue by ring630** [ansys/pyedb#395]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

PyEDB ERROR: ATTRIBUTE ERROR on _export_layer_stackup_to_json
PyEDB ERROR: 'Material' object has no attribute '_json_format'
PyEDB ERROR:   File "D:\_pycharm_project\pyaedt-examples\venv\lib\site-packages\pyedb\dotnet\edb_core\stackup.py", line 789, in export
PyEDB ERROR:     return self._export_layer_stackup_to_json(fpath, include_material_with_layer)
PyEDB ERROR:   File "D:\_pycharm_project\pyaedt-examples\venv\lib\site-packages\pyedb\dotnet\edb_core\stackup.py", line 861, in _export_layer_stackup_to_json
PyEDB ERROR: Method arguments: 
PyEDB ERROR:     output_file = stk.json 

### Steps To Reproduce

edbapp.stackup.export("stk.json")

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

all

**Comment by ring630** [comment]
Update
The problem only exist in non grpc mode.

**Comment by SMoraisAnsys** [comment]
@ring630 This issue should have been fixed with #468, feel free to open it back if that's not the case !
