### ISSUE TITLE
Consolidate download method

### ISSUE THREAD

**Issue by dcrawforAtAnsys** [ansys/pyedb#402]
### Description of the current limitations

``pyedb.misc.downloads`` has virtually identical functionality to ``pyaedt.downloads``. Changes to the latter have not yet propagated to the former so it may be advisable to deprecate ``pyedb.misc.downloads`` in favor of using pyaedt.

### Code sample expected

See https://github.com/ansys/pyaedt/blob/main/pyaedt/downloads.py

**Comment by ring630** [comment]
@dcrawforAtAnsys removed downloads.py from pyedb. Examples are corrected.

**Comment by ring630** [comment]
Reverted since pyedb must be standalone.
