### ISSUE TITLE
Bug located in edbapp.nets.plot()

### ISSUE THREAD

**Issue by ring630** [ansys/pyedb#405]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Pads and voids are not plotted.

### Steps To Reproduce

edbapp.nets.plot()

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

all

**Comment by gkorompi** [comment]
This is not yet supported. Please see enhancement request: issue #195

**Comment by svandenb-dev** [comment]
closing this issue since it is duplicated with issue #195
