### ISSUE TITLE
Bug located in ...add_length_mesh_operation function deletes the Sweep of the setup

### ISSUE THREAD

**Issue by gkorompi** [ansys/pyedb#431]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

NA

### Steps To Reproduce

NA

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

na

**Comment by ring630** [comment]
@gkorompi fixed.
