### ISSUE TITLE
rapter setup returns EDB API objects

### ISSUE THREAD

**Issue by ring630** [ansys/pyedb#447]
@svandenb-dev 
https://github.com/ansys/pyedb/blob/bd06c01937129fdf8c042772aa82563c2f1bb8f9/src/pyedb/dotnet/edb_core/edb_data/raptor_x_simulation_setup_data.py#L79

**Comment by ring630** [comment]
@svandenb-dev  can you reuse below property

https://github.com/ansys/pyedb/blob/bd06c01937129fdf8c042772aa82563c2f1bb8f9/src/pyedb/dotnet/edb_core/utilities/simulation_setup.py#L167-L172

**Comment by svandenb-dev** [comment]
Yes will add it when the previous PR is merged
