### ISSUE TITLE
Bug located in import stackup

### ISSUE THREAD

**Issue by ring630** [ansys/pyedb#487]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Pad defintion cannot find layer if layer is renamed. 
<img width="821" alt="image" src="https://github.com/ansys/pyedb/assets/27995305/b1de3665-71d8-4649-b873-d76f1e8c68e9">

### Steps To Reproduce

Pad defintion cannot find layer if layer is renamed. 

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

all

**Comment by pyAnsysUser** [comment]
@ring630 has progress been made on this issue? Is there a different underlying problem behind this? I am running into a similar issue (renaming, not from import)

**Comment by pyAnsysUser** [comment]
Nevermind, it looks like this behavior is corrected. My issue stems from having a polygon pad, which does not yet appear to be supported by the padstack def class

**Comment by ring630** [comment]
> @ring630 has progress been made on this issue? Is there a different underlying problem behind this? I am running into a similar issue (renaming, not from import)

@pyAnsysUser there is no underly problem. This bug is a mis-report. That's correct, polygon pad is not support. Please submit an issue.

**Comment by pyAnsysUser** [comment]
hello,
it sounds like, padstack class will refactor. I have much refactor to do myself, I will not pester if this issue resolves itself until I need the change.
