### ISSUE TITLE
Bug located in ...create_hfss_setup returns raptorx error

### ISSUE THREAD

**Issue by gkorompi** [ansys/pyedb#503]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

ΝΑ

### Steps To Reproduce

from pyedb.dotnet.edb import Edb
edbapp = Edb(r"C:\Users\gkorompi\Downloads\Case3_fixedModel_intersections_removed_circuit.aedb",edbversion="2023.2")
edbapp.version
edbapp.create
setup = edbapp.create_hfss_setup("test")

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

na

**Comment by ring630** [comment]
@SMoraisAnsys @svandenb-dev this is critical. Customer will not be able to create hfss setup without AEDT 2024.2. We need an urgent release revert.

**Comment by SMoraisAnsys** [comment]
From what I could see on my laptop, the error is raised for both RaptorX and HFSSPISimulationSettings.
Any other problems ?
Want me to try to fix this issue ?

**Comment by ring630** [comment]
@SMoraisAnsys the problem is raptor doesn't exist in EDB API before 24.1.
