### ISSUE TITLE
Add ...max_limit in configuration format.

### ISSUE THREAD

**Issue by gkorompi** [ansys/pyedb#512]
### Description of the feature

create current sources creates a pin group on the negative terminal. I would like for it to choose the nearest reference for each pin instead:

![image](https://github.com/ansys/pyedb/assets/156683163/4f32c4af-b9e1-4856-b668-205d1b43c755)

**Comment by gkorompi** [comment]
It does not work, it tries to create a pin group i am attaching the error message: 
![image](https://github.com/ansys/pyedb/assets/156683163/e1074aee-1c71-420d-bd89-8c31a5482177)

**Comment by ring630** [comment]
@gkorompi it is merged now. Can you try again?
