### ISSUE TITLE
Bug located in RaptorX setup, advanced mesh settings

### ISSUE THREAD

**Issue by gfetsis** [ansys/pyedb#521]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Trying to define an advanced mesh setting in a RaptorX setup returns an error. Mesh frequency is defined as a string but it returns the following

 *\.venv\Lib\site-packages\pyedb\dotnet\edb_core\edb_data\raptor_x_simulation_setup_data.py", line 232, in mesh_frequency
    self._advanced_settings.MeshFrequency = EdbValue(value).tostring
                                            ^^^^^^^^^^^^^^^^^^^^^^^^
  *\.venv\Lib\site-packages\pyedb\dotnet\edb_core\edb_data\edbvalue.py", line 68, in tostring
    return self._edb_obj.ToString()
           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'ToString'

### Steps To Reproduce

Define a RaptorX setup,
setup= edbapp.create_raptorx_setup(name="RaptorX1_Setup")

Enable advanced mesh frequency,
setup.settings.advanced_settings.use_mesh_frequency=True

Set a value for the advanced mesh frequency,
setup.settings.advanced_settings.mesh_frequency='10GHz'

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

-

**Comment by gkorompi** [comment]
This is handled by Georgios Fetsis. It is assigned to me until he gets access as a dev.

**Comment by gkorompi** [comment]
@svandenb-dev
