### ISSUE TITLE
Bug located in raptor_setup.

### ISSUE THREAD

**Issue by gkorompi** [ansys/pyedb#522]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

When importing a file with raptor_setup, 3DL fails to change to 3DIC mode. 

### Steps To Reproduce

NA

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

NA

**Comment by svandenb-dev** [comment]
@gkorompi this is not a bug and has to be managed by AEDT. There is no IC mode manage by EDB.

**Comment by gkorompi** [comment]
https://tfs.ansys.com:8443/tfs/ANSYS_Development/Portfolio/_workitems/edit/1054807

**Comment by gkorompi** [comment]
@svandenb-dev
