### ISSUE TITLE
edb.configuration.load fail to set rlc_model

### ISSUE THREAD

**Issue by ring630** [ansys/pyedb#538]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

edb.configuration.load fail to set rlc_model

### Steps To Reproduce

components = [
            {
                "reference_designator": "C375",
                "enabled": False,
                "value": 100e-9,
            },
            {
                "reference_designator": "L2",
                "part_type": "resistor",
                "rlc_model": [
                    {
                        "type": "series",
                        "capacitance": "100nf",
                        "inductance": "1nh",
                        "resistance": "0.001",
                        "p1": "1",
                        "p2": "2"
                    }
                ]
            }
        ]
        data = {"components": components}
        edbapp = edb_examples.get_si_verse()
        assert edbapp.configuration.load(data, apply_file=True)
        assert edbapp.components["C375"].enabled == False
        assert edbapp.components["C375"].value == 100e-9
        assert edbapp.components["L2"].type == "Resistor"
        edbapp.close()

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

all

**Comment by svandenb-dev** [comment]
@ring630 can we close this issue ?

**Comment by ring630** [comment]
@svandenb-dev this bug is not fixed.
