### ISSUE TITLE
Bug located in add_frequency_sweep

### ISSUE THREAD

**Issue by ring630** [ansys/pyedb#569]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

add_frequency_sweep doesn't set frequency sweep correctly.

### Steps To Reproduce

add_frequency_sweep doesn't set linear scale frequency sweep correctly.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

all

**Comment by gkorompi** [comment]
@ring630  https://github.com/ansys/pyedb/issues/518
