### ISSUE TITLE
Bug located in pyedb documentation

### ISSUE THREAD

**Issue by ring630** [ansys/pyedb#603]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

Example link is broken

![image](https://github.com/ansys/pyedb/assets/27995305/a847aec8-9434-451c-9b3d-1544a426f546)

### Steps To Reproduce

https://edb.docs.pyansys.com/version/stable/index.html

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

all

**Comment by SMoraisAnsys** [comment]
@ring630 This got fixed with changes in the `gh-pages` branch and documentation fixes
