### ISSUE TITLE
documentation link error -> search for placement_layer ended in page 404 error

### ISSUE THREAD

**Issue by Ronaldo-SIPI** [ansys/pyedb#647]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

if you search for placement_layer as text in the GitHub search bar the results ended in a page 404 error
search for
![image](https://github.com/ansys/pyedb/assets/119055187/a004e680-bb25-44f0-bfaf-91333211403a)
end up here
![image](https://github.com/ansys/pyedb/assets/119055187/2795766c-00ab-45c6-a9d9-96f617b10678)

### Steps To Reproduce

search for placement_layer in the EDB documentation

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

annotated-types==0.7.0
ansys-pythonnet==3.1.0rc3           
attrs==23.2.0                       
cffi==1.16.0                        
clr-loader==0.2.6                   
colorama==0.4.6                     
defusedxml==0.7.1                   
exceptiongroup==1.2.1               
fonttools==4.53.0                   
fpdf2==2.7.9                        
iniconfig==2.0.0                    
jsonschema==4.22.0                  
jsonschema-specifications==2023.12.1
numpy==1.26.4                       
packaging==24.1                     
pillow==10.3.0
pluggy==1.5.0
plumbum==1.8.3
psutil==5.9.8
pyaedt==0.9.4
pycparser==2.22
pydantic==2.7.3
pydantic_core==2.18.4
pyedb==0.12.1
pytest==8.2.2
pytomlpp==1.0.13
pywin32==306
referencing==0.35.1
rpds-py==0.18.1
rpyc==6.0.0
Rtree==1.2.0
toml==0.10.2
tomli==2.0.1
typing_extensions==4.12.1

**Comment by SMoraisAnsys** [comment]
@Ronaldo-SIPI Hi, thanks for reaching us with that issue ! I've tried to reproduce your error but I can't success to do it.

I've performed a search with `"placement_layer"` and every line proposed was working. Can you let me know which one was failing and provide the associated failing URL ?

**Comment by Ronaldo-SIPI** [comment]
sorry I mentioned the wrong property
it is the get_pin_postion property 
where the source point to the generic_methods.py 

![image](https://github.com/ansys/pyedb/assets/119055187/4db29eee-f3c5-4791-804f-c63a0d2eb985)
sorry
placement_layer is ok also on my side

**Comment by SMoraisAnsys** [comment]
I'm still not able to reproduce this error haha, could it be related to an holder version of the documentation ?
When I search for `get_pin_position` and end up in the same page as you, clicking on source redirect me to https://github.com/ansys/pyedb/blob/main/src/pyedb/dotnet/edb_core/components.py#L2378-L2409

So I can't end up with the "404 not found" page or the issue on the code line.
Can you give me more information so that I can help you ?

**Comment by Ronaldo-SIPI** [comment]
@SMoraisAnsysI try it today and I must say it works
last week I had this issue
so please close this issue
sorry Ronaldo

**Comment by Ronaldo-SIPI** [comment]
closed it works as expected

**Comment by SMoraisAnsys** [comment]
@Ronaldo-SIPI JSYK your issue made me realize we had 2 other issues related to the documentation. Hopefully the new release will remove them and you shouldn't face this behavior anymore (I was able to reproduce it through multiple back and forth in the documentation but can't tell how to reproduce it).
