### ISSUE TITLE
change lower.elevation value of a padstack instance to a float value like the upper.elevation

### ISSUE THREAD

**Issue by Ronaldo-SIPI** [ansys/pyedb#648]
### Description of the current limitations

to have a consistent value for upper and lower elevation of a pad stack instance 
please change the lower.elevation to a float value

![image](https://github.com/ansys/pyedb/assets/119055187/f3080341-2781-47c5-98e9-be90426f4f70)

may this is a scaling issue but it would be good to only a float value instead of a mix between scientific and float notation
I see the lower scientific notation in PyCharm and Jupyter Notebook

may not relevant

**Comment by ring630** [comment]
@Ronaldo-SIPI python print float value in different appearance.

![image](https://github.com/ansys/pyedb/assets/27995305/c6235267-906d-4124-81e3-6b926da692cd)

**Comment by Ronaldo-SIPI** [comment]
ok then I close this and we must live with that appearance
LGTM
