### ISSUE TITLE
Expose additional attributes of capacitors

### ISSUE THREAD

**Issue by mahesh-dhanekula** [ansys/pyedb#697]
### Description of the feature

Expose attributes for capacitors from library accessed through [get_vendor_libraries](https://edb.docs.pyansys.com/version/0.22/api/_autosummary/pyedb.dotnet.edb_core.components.Components.get_vendor_libraries.html#get-vendor-libraries)
1. ESL
2. ESR
3. Temperature Rating
4. Variation of value
Should also consider reading user defined component libraries

**Comment by svandenb-dev** [comment]
@mahesh-dhanekula L, C, ESL and ESR values are now supported. However Temperature rating and Variation value is not possible since the information is missing in the lib folder. I will close this issue you can reopen a new one if you found a bug. Thanks
