### ISSUE TITLE
Bug located in edb = Edb(project, edbversion)

### ISSUE THREAD

**Issue by yangwg98** [ansys/pyedb#706]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

I used pyinstaller.exe --onefile test.py to translate the code. 
it reports one error " clr_loader.util.clr_error.ClrError: 0x80131509: COR_E_INVALIDOPERATION => An operation is not legal in the current state.

No issue with cx_Freeze.

the code:
from pyedb import Edb
# Load brd to create siw file ---started-------------------------------
project = r'C:\test.brd'
edb = Edb(project, edbversion='24.1')

![brd_load_issue](https://github.com/user-attachments/assets/59985a18-61ea-4f58-9e2c-5bcab6ac7b3b)

### Steps To Reproduce

use "pyinstaller.exe --onefile test.py to translate the code" to transfer the code
and then open it.
the error is reported in command window

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

altgraph==0.17.4
annotated-types==0.7.0
ansys-pythonnet==3.1.0rc3
cffi==1.16.0
clr-loader==0.2.6
ironpython-pytest==0.5.0
numpy==1.26.4
packaging==24.0
pefile==2023.2.7
pycparser==2.22
pydantic==2.7.4
pydantic_core==2.18.4
pyedb==0.18.0
pyinstall==0.1.4
pyinstaller==6.8.0
pyinstaller-hooks-contrib==2024.7
PyWavefront==1.3.3
pywin32==306
pywin32-ctypes==0.2.2
Rtree==1.2.0
setuptools==70.0.0
toml==0.10.2
typing_extensions==4.12.2
wheel==0.43.0

**Comment by ring630** [comment]
@yangwg98 the compiler tools are usually not stable and needs lots of fine tuning to make it work. The error you have might be a problem in pyinstaller. I recommend you to run pyedb in python environment.

If you still want to compile your code with pyedb, please try cx_freeze.

**Comment by yangwg98** [comment]
Thanks @ring630, I have started to use cx_freeze for my package now.
Will pyinstaller fix this issue？

**Comment by ring630** [comment]
@yangwg98 That's I cannot know. I have limited experience with pyinstaller and cx_freeze.

**Comment by yangwg98** [comment]
Thanks @ring630 , do you know which path can submit this issue to fix pyinstaller?

**Comment by ring630** [comment]
@yangwg98 Sorry, I don't know. I don't have much knowledge on pyinstaller.

**Comment by yangwg98** [comment]
[AMD Official Use Only - AMD Internal Distribution Only]

Ok, np, thanks.
I have found the solution.

Thanks,
Tony Yang
