### ISSUE TITLE
"build_simulation_project" function reports an error

### ISSUE THREAD

**Issue by Ivanz7** [ansys/pyedb#711]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

    edbapp.build_simulation_project(sim_setup)
  File "C:\Program Files\Python\lib\site-packages\pyedb\dotnet\edb.py", line 3293, in build_simulation_project
    self.nets.classify_nets(simulation_setup.power_nets, simulation_setup.signal_nets)
AttributeError: 'NoneType' object has no attribute 'classify_nets'

### Steps To Reproduce

When running the example "Build a signal integrity project" in https://edb.docs.pyansys.com/version/stable/user_guide/build_simulation_project/build_signal_integrity_project.html

It reports the error "AttributeError: 'NoneType' object has no attribute 'classify_nets'"

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

annotated-types==0.7.0
ansys-pythonnet==3.1.0rc3
attrs==24.1.0
cffi==1.16.0
clr-loader==0.2.6
defusedxml==0.7.1
fonttools==4.53.1
fpdf2==2.7.9
jsonschema==4.23.0
jsonschema-specifications==2023.12.1
numpy==1.26.4
pandas==2.2.2
pillow==10.4.0
plumbum==1.8.3
psutil==6.0.0
pyaedt==0.9.10
pycparser==2.22
pydantic==2.8.2
pydantic_core==2.20.1
pyedb==0.23.0
python-dateutil==2.9.0.post0
pytomlpp==1.0.13
pytz==2024.1
pywin32==306
referencing==0.35.1
rpds-py==0.19.1
rpyc==6.0.0
Rtree==1.3.0
scikit-rf==1.2.0
scipy==1.14.0
six==1.16.0
toml==0.10.2
typing_extensions==4.12.2
tzdata==2024.1

**Comment by ring630** [comment]
@svandenb-dev

**Comment by ring630** [comment]
@Ivanz7 I am closing this issue. I you still have the probelm, please submit a new issue.
