### ISSUE TITLE
BUG: Example error with AEDT 2024.2

### ISSUE THREAD

**Issue by SMoraisAnsys** [ansys/pyedb#722]
@svandenb-dev @ring630 There is a problem when moving to AEDT 2024.2 and it is related to the method https://edb.docs.pyansys.com/version/dev/api/_autosummary/pyedb.dotnet.edb_core.hfss.EdbHfss.create_differential_wave_port.html#create-differential-wave-port

The `example 04_edb_parametrized_design.py` is currently not working with AEDT 2024.2. Here is the change of behavior that we have been able to detect and might be the reason for the failure. When one calls 

```python
edb.hfss.create_differential_wave_port(
    trace_p[0].id,
    ["0.0", "($ms_width+$ms_spacing)/2"],
    trace_n[0].id,
    ["0.0", "-($ms_width+$ms_spacing)/2"],
    "wave_port_1",
)
```
the code sets the name of the positive port as `wave_port` and does nothing about the negative port. Then, when the project is loaded in `Hfss3dLayout` (through pyaedt), the ports are named `wave_port_1:T1` and `wave_port_1:T2` in AEDT. However, with AEDT 2024.2, the negative port is named randomly following the pattern `Terminal__.....`. This seems to be a problem as afterward, we are not able to solve the project in `Hfss3dLayout`.

Samuel proposed the changes in https://github.com/ansys/pyedb/pull/713/commits/68b393a08d45f89ad3a843cad939ce52b1ac3eee but they have some extra effects as `edb.ports` will not have the same values as before.

Related PR #713

**Comment by SMoraisAnsys** [comment]
Btw, this also impacts `pyaedt-examples`, see
https://github.com/ansys-internal/pyaedt-examples/pull/200

**Comment by ring630** [comment]
#724 this PR should fix the issue.

**Comment by svandenb-dev** [comment]
@SMoraisAnsys @ring630 can we close this issue ?
