### ISSUE TITLE
Add ..."hole_diameter" in pyedb.dotnet.edb_core.edb_data.padstacks_data.EDBPadstackInstance

### ISSUE THREAD

**Issue by linmingchih** [ansys/pyedb#723]
### Description of the feature

Please consider to add the properties in the class.
![image](https://github.com/user-attachments/assets/2e9b9fad-9408-4c75-bbba-74d0df17cc8c)

**Comment by hui-zhou-a** [comment]
@linmingchih once it's merged, you can set hole override by 

`edbapp.padstacks.instances_by_name["Via998"].properties = {"hole_override_enabled":True,
                                                   "hole_override_diameter": "0.5mm"}`
